### PR TITLE
Add eslint and fix some deepsource issues

### PR DESCRIPTION
**Pull request by marekrozmus**
Related to #27

Cleaned up the code and added [Eslint](https://eslint.org/).
If you think it is OK then we could think of some code standards. 
Please let me know if [Prettier](https://prettier.io/) integration is needed :)

### CODE REVIEW

**Comment by audreyfeldroy** [comment]
Yay, I love ESLint! 

Since this touches a lot of files, I'd love to get this PR in ASAP before we get too many PRs from others. You up to resolving the conflicts? If you're busy or away, I can do it but it might not be until 3pm PST.

I'm very interested in code standards. Any particular ones you think we should adopt? Generally I like to link to someone else's already-maintained standards and adopt them as ours, with additions at the bottom. I'm somewhat flexible about this approach, though.

Prettier integration would be awesome too.

**Comment by marekrozmus** [comment]
I can merge all tomorrow and fix all new issues :)
Unless you really want to do that today then go ahead :)

**Comment by marekrozmus** [comment]
Hi :) @audreyfeldroy - most of stuff is fixed. We should merge this one ASAP.

How should we set up depth of JSX? We got this (issue)[https://deepsource.io/gh/margaritahumanitarian/helpafamily/run/d081bccd-9f96-4713-81d2-96ecd3303c3f/javascript/JS-0415]
 and we just should set something for linter.

**Comment by audreyfeldroy** [comment]
> How should we set up depth of JSX?
Interesting, I looked at that and am not sure. I'm getting sleepy...how about I merge this PR now, then you file that as a separate issue and people can chime in?

**Comment by audreyfeldroy** [comment]
You're amazing @marekrozmus. Your thoughtful work in this PR is such a huge help.

**Pull request merged**
