### PR TITLE
Improve Anyone In Need & Other Checkbox Functionality

### PR DESCRIPTION
**Pull request by rathijitpapon**
Improve anyone in need toggle functionality. Previously it disabled the other checkboxes. Now, it will check the other checkboxes & open the option for users to uncheck one or multiple checkboxes. Also, an error handling alert is added which will ask users to check at least one checkbox.

image

### CODE REVIEW

**Comment by RedFox0x20** [comment]
I like the react optimisations you've done to remove duplicate code using the `.map` method.

It may be worth modifying the `handleSubmit` method further; Submitting a response with the changes made results in the following output on the donation form
> Help Students in Need, People of Color in Need, Immigrants in Need, Seniors in Need

This output to me is a bit messier and unnecessarily long, in comparison to the previous messages which would only show
> Help Anyone in need

I also run into an issue within the development environment where not selecting a donation amount causes an error
`SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data`
It appears that the check here does not execute causing the process to continue with a zero value which causes an error within the stripe library where it is expecting a non-zero value.
```
if (event.target.amount.value === 0) {
      alert("Please choose an amount to give");
      return;
    }
```

**Comment by rathijitpapon** [comment]
@RedFox0x20 Thanks for your suggestions. I have just fixed the amount selection bug & anyone in need stripe level

**Comment by audreyfeldroy** [comment]
Thanks for submitting this @rathijitpapon, and thanks for the review @RedFox0x20! I'm about to jump into meetings but will take a closer look in a few hours.

Everyone, in terms of minimizing file conflicts, any preference if I merge this or #56 by @marekrozmus first?

**Comment by rathijitpapon** [comment]
> Everyone, in terms of minimizing file conflicts, any preference if I merge this or #56 by @marekrozmus first?

I think u can merge other PRs before merging @marekrozmus's PR. Otherwise, conflicts can occur.

**Review by audreyfeldroy — CHANGES_REQUESTED** [review]
I'm reviewing this very carefully. @rathijitpapon you have a great eye for detail and I'd like to merge at least part of this PR.

I do like how in `main`, the cause in Stripe checkout show up as "Help Anyone in need" when the toggle is on. @RedFox0x20, you were very thoughtful to implement that. The only correction there would be to capitalize the "N" in "Need".

Playing with it from a UX perspective, I see arguments for both the original UX @RedFox0x20 implemented and for @rathijitpapon's revision. Something feels like it could be simplified a little. I'm reading @johnmaeda's The Laws of Simplicity. and [Law 1: Reduce](http://lawsofsimplicity.com/los/law-1-reduce.html) talks about hiding controls that aren't in use, such as how good DVD players hide the rarely-used time settings behind a hinged door panel.

Brainstorming simplifications...I think hiding the checkboxes when "Anyone in Need" is toggled on would work nicely. Want to try implementing that? Or perhaps this inspires you with other form UX ideas?

**Comment by rathijitpapon** [comment]
> Brainstorming simplifications...I think hiding the checkboxes when "Anyone in Need" is toggled on would work nicely. Want to try implementing that? Or perhaps this inspires you with other form UX ideas?

Do u want something like this?

image

**Comment by audreyfeldroy** [comment]
Yes, that's exactly what I was thinking 🙂

**Comment by rathijitpapon** [comment]
> Yes, that's exactly what I was thinking

U can check this now.

**Comment by audreyfeldroy** [comment]
That's really nice @rathijitpapon. Can you toggle "Anyone in Need" on by default?

**Comment by rathijitpapon** [comment]
> That's really nice @rathijitpapon. Can you toggle "Anyone in Need" on by default?

Yeah, I have done it.

**Comment by audreyfeldroy** [comment]
@rathijitpapon it looks and works great. 

@RedFox0x20 since this builds upon your work and your initial code review was very good, would you like to try giving this a second code review and/or try resolving conflicts?

**Review by RedFox0x20 — APPROVED** [review]
@audreyfeldroy A fantastic set of changes, a much better implementation of an idea I played around with during my initial implementation of the `Anyone in need` button. Clear improvements to the code overall, @rathijitpapon probably has a good bit more experience in using React than I do allowing for these improvements haha.

Sadly I cannot test properly currently as I am receiving an authentication error when clicking the donate button, however if you can see that it is working correctly then everything looks okay to me!

Nice interaction, clear link between elements. Great work!

**Pull request merged**
