### PR TITLE
Fix deepsource missing key issue

### PR DESCRIPTION
**Pull request by marekrozmus**
Related to #27

### CODE REVIEW

**Comment by audreyfeldroy** [comment]
Thanks so much for working on the missing key issue @marekrozmus! I appreciate it so much. Starting your code review...

**Comment by audreyfeldroy** [comment]
To clarify, are you referring to this issue?
> Missing key for the property JS-0414
https://deepsource.io/gh/margaritahumanitarian/helpafamily/issue/JS-0414/

**Comment by marekrozmus** [comment]
yes, this is the one :) But I see that I should sort the imports somehow

**Comment by audreyfeldroy** [comment]
Cool. Don't worry about the import sorting, it's technically outside the scope of JS-0414 and can be in a later PR. 

I love that you're thinking about code quality improvements and truly appreciate that kind of help!

**Comment by marekrozmus** [comment]
I think I can merge changes later on and add more fixes here: #56 - what do you think? 🙂

**Comment by audreyfeldroy** [comment]
This PR was awesome, thanks @marekrozmus!

**Pull request merged**
