### PR TITLE
added form for donations

### PR DESCRIPTION
**Pull request by ozer619**
The UI is not perfect please guide what else should be done.

### CODE REVIEW

**Review by RedFox0x20 — COMMENTED** [review]
The form looks good!

Only changes I would make are regarding mobile responsivity and the yellow background.

Just curious about the many, many `{' '}` some of which don't appear to be related to anything or don't appear as they would provide any value?

**Comment by ozer619** [comment]
Ok maybe i remove {' '} these and so about the color white's good?


> The form looks good!
> 
> Only changes I would make are regarding mobile responsivity and the yellow background.
> 
> Just curious about the many, many `{' '}` some of which don't appear to be related to anything or don't appear as they would provide any value?

**Comment by RedFox0x20** [comment]
Sounds like a plan, may be worth just seeing if it makes any difference at all, easy enough to reset the branch to put them back in if they actually have a purpose that I'm missing.

**Comment by ozer619** [comment]
> Sounds like a plan, may be worth just seeing if it makes any difference at all, easy enough to reset the branch to put them back in if they actually have a purpose that I'm missing.

Im sorry they were quiteuseless also can u suggest me a good color for the back?

**Comment by RedFox0x20** [comment]
Personally I like the blank contrast of the black and white, it keeps forms tidy. It's completely a personal preference to be honest, you can leave it in for now if you like it, just up to other reviews for things like that. It's not bad on desktop as a sort of "focus of attention" but on mobile it looked a touch out of place to me. // I'll be doing another sweep of mobile changes soon enough anyway so I wouldn't worry too much about it.

**Comment by audreyfeldroy** [comment]
Try `bg-green-300` for form color, which is sort of close to the MHF logo colors. It's okay if it's not perfect, we can iterate.

**Comment by ozer619** [comment]
> Try `bg-green-300` for form color, which is sort of close to the MHF logo colors. It's okay if it's not perfect, we can iterate.

I have made the required changes.

**Comment by audreyfeldroy** [comment]
Just saw your comment @RedFox0x20 about form colors. Color is easy to iterate on later. I'll go ahead and merge this. Great work @ozer619 and great reviewing @RedFox0x20.

**Pull request merged**
