### PR TITLE
unit test Card component

### PR DESCRIPTION
**Pull request by idiglove**
### This PR: 
* Coverage should include nested files
* unit tests in Card component
* I need help on the onClick mock function, I can't seem to make it work

### Self-Review Checklist
- [x] PR title is clear with proper spelling and grammar
- [x] PR description contains a bulleted list of changes contained in the PR
- [ ] PR links to relevant issues, with keywords to auto-close any issues fully resolved upon merge
- [x] All automated checks passed
- [x] Any variables introduced are named clearly and explicitly

### CODE REVIEW

**Comment by idiglove** [comment]
> @idiglove Thank you for doing this! I left you the error message that comes in the test coverage from github to work off of.

Hi, yea Im having a hard time making it work. Can you help me? I dont know what Im doing wrong 😬

**Comment by idiglove** [comment]
@LowLifeArcade I got it working now :)

**Comment by idiglove** [comment]
image

**Comment by LowLifeArcade** [comment]
Sorry for the delay @idiglove! Great job fixing this :) Merging now! 🌮 ✨

**Pull request merged**
