### PR TITLE
Add Prettier support

### LINKED ISSUE #65: Enable DeepSource transformer for Prettier?
From https://deepsource.io/gh/margaritahumanitarian/helpafamily/history/transforms :

> Enable transformers in `.deepsource.toml` to automatically transform all incoming code with auto code formatters.

This might be a good way to auto-run Prettier @marekrozmus? Unless you have another idea in mind?
See https://deepsource.io/docs/transformer/prettier

### PR DESCRIPTION
**Pull request by marekrozmus**
Closes #65

### CODE REVIEW

**Comment by marekrozmus** [comment]
@audreyfeldroy please check the "checks" above ;)
It looks like you need to add some additional permissions for Transformers.

**Comment by audreyfeldroy** [comment]
Join our DeepSource team via https://deepsource.io/invitation/u9KI3eiHcWAS8uBvw9Zi0rNhUNQa15/

Then I'll grant you extra rights

**Comment by audreyfeldroy** [comment]
I'm having trouble figuring out how to grant transformers permission to run. I've given you maintainer rights on this repo so you can help me figure out 🙂

**Comment by audreyfeldroy** [comment]
It's almost like there's a bug in DeepSource. I click "Setup Transformers" here:

2021-08-19 at 03 04 08

and I get this:

2021-08-19 at 03 04 52

Then, clicking "Sync repositories" does nothing, and searching for "helpafamily" brings up no results. Hmm.

**Comment by audreyfeldroy** [comment]
DeepSource wants me to upgrade to add you as a member @marekrozmus. Looks like we're at our max number of seats.

@RaphaelGC7 I'll remove you temporarily but can add you back later 🙂 Then I can add @marekrozmus

**Comment by audreyfeldroy** [comment]
Check your email for the invite to be an admin on DeepSource @marekrozmus!

**Comment by marekrozmus** [comment]
Maybe you need to update the permissions for DeepSource on Github / Project Settings / Integrations?
I cannot see that settings here so I cannot do much.

**Comment by audreyfeldroy** [comment]
Thanks for the idea about Project Settings / Integrations. I checked that and didn't see anything additional I can toggle. I've given you full admin rights on this repo now, see if you can see anything.

**Comment by audreyfeldroy** [comment]
I've also granted you owner rights on the org for now, since some of the DeepSource permissions are org-level.

**Comment by marekrozmus** [comment]
Oh, it looks like that this feature is in paid version :/

So please roll back all permissions for me - we cannot do anything about it.

I can remove the transformers from deepsource toml config file

**Comment by audreyfeldroy** [comment]
If you still can't see anything, I think it's likely a bug in DeepSource. We can ask in https://deepsourceusers.slack.com/ - but I'll give you a chance to look into it first.

**Comment by audreyfeldroy** [comment]
Oh no! That's too bad.

**Comment by marekrozmus** [comment]
It is hard to find what is for open source and what is not. So my guess is that it is for paid version. But you can always ask them.

**Comment by audreyfeldroy** [comment]
I'll leave the permissions as-is for now in case you want to try a different way of auto-running Prettier, like via a GitHub action or something else.

**Comment by audreyfeldroy** [comment]
Thanks so much for all your patience and help @marekrozmus 🙏

**Comment by marekrozmus** [comment]
@audreyfeldroy I've remove the tranform setting and merged latest changes.
If you like you can merge it as it is - at least in editors prettier should fix some stuff on save.

**Comment by audreyfeldroy** [comment]
Merged, thanks @marekrozmus!

**Comment by sanket-deepsource** [comment]
Hey @audreyfeldroy! I'm the founder of DeepSource — just wanted to chime in here. Transformers are available for free for all open-source projects without any restrictions. The only thing you'll need is to additionally install the Autofix app from your repository settings (that gives DeepSource access to automatically commit the formatted code on every PR).

I hope this helps. Please let me know if I can be of help in any way! :)

**Pull request merged**
