### PR TITLE
Implement subpages for navbar

### LINKED ISSUE #95: Implement navbar items as card categories
When you click "In-Kind" in the navbar, it should only show the cards that are in-kind donations: 
* Laptop for Families
* Hygiene Kits

When you click "Fund" it should show all the cards where the button goes to Stripe checkout.

We don't have any "Give Your Time" cards yet, but we will soon. Those are cards describing how people can volunteer, e.g. doctors can give 1+ hour per week of pro bono service to the humanitarian clinic.

### PR DESCRIPTION
**Pull request by marekrozmus**
This is proposal for page layout component  and subpages. Should be easier to maintain rather then array of cards.

All comments are welcome 🙂 

Closes #95

### CODE REVIEW

**Comment by GrungeKarma** [comment]
I like where this is going. If we go this route, keeping any cards on the main page comes off to me as redundant. Personally, I like the idea of keeping the cards on the main page and only have a home link to lead to the main site again. Implementing something like this [https://codemyui.com/div-fullscreen-click/] with card rings. These are just my opinions though. I would be happy to help work with any direction we chose to go.

**Comment by RedFox0x20** [comment]
The "subpages" work quite well like this, I sort of get the feeling they're more "categories" or cards rather than "pages". Perhaps they are better suited as separate sections on the main page i.e. following a `header > cards > header > cards` sort of flow where the navbar would link to the individual sections.

Alternatively this system could work if the cards were each given an identifying feature i.e. colour associated borders, that would allow cards to be easily identified by group and linking this colour back into the navbar.

---

@GrungeKarma Interesting suggestion with
> Implementing something like this https://codemyui.com/div-fullscreen-click/ with card rings.

The current content provided by the cards doesn't necessarily warrant the addition of this, however it could be useful in the future for certain events to allow for a "detailed" view containing a picture gallery (or slideshow) of real events that have taken place, to allow people to see what their donation goes towards.

**Comment by GrungeKarma** [comment]
@RedFox0x20 We could group the cards with color using the hover rings with colors and separate components for the card groups. I will work on a proposal once this pull request is dealt with. So I know exactly where we sit right now.

**Review by audreyfeldroy — APPROVED** [review]
All looks great @marekrozmus. There's a lot of really good refactor work in here, and the implementation is very nice. Thanks for all your hard work on this PR.

@GrungeKarma and @RedFox0x20 Really appreciate your comments here. I thought carefully about them and will respond further below.

**Comment by audreyfeldroy** [comment]
>  keeping any cards on the main page comes off to me as redundant

At the moment it feels a bit funny, but when we grow to have 30+ cards it'll help a lot. 

About the expanding divs, I'm not 100% sure, but I'd be interested to see an example of how it might work with a card that has additional photos. @GrungeKarma [here](https://github.com/margaritahumanitarian/media-kit/tree/main/photos) are some photos you can experiment with to add content to the 2 corresponding cards. I can get you more photos as needed for any of the cards or you can ask in chat for any kinds of photos you'd like.

**Comment by GrungeKarma** [comment]
I will take a look at it tomorrow. I need to figure out how to achieve the effect with Tailwind. I am sure it is there somewhere.

**Pull request merged**
