### PR TITLE
Replace alerts with modals and update select usage

### PR DESCRIPTION
**Pull request by marekrozmus**

### CODE REVIEW

**Comment by audreyfeldroy** [comment]
Oh wow @marekrozmus, thank you for this. I just tried out the Vercel deploy preview and it worked perfectly. I'm off to bed but will review this tomorrow (today).

**Comment by marekrozmus** [comment]
It is just a proposal. I will fix the conflicts today.

**Review by RedFox0x20 — APPROVED** [review]
Very nice change, relating to #27 

Works well on both small and larger screens. Nicely done!

Also updates DaisyUI, partially out of scope for the PR but not a big deal.

**Comment by marekrozmus** [comment]
I needed to update daisyui as I needed the latest functionality.

**Comment by marekrozmus** [comment]
@audreyfeldroy will we gonna merge this :)?

**Review by audreyfeldroy — APPROVED** [review]
I reviewed this the best I could, but I'll admit my React knowledge isn't deep enough to fully understand it all. I've seen enough of @marekrozmus's PRs by now to trust his depth of React experience there, so I'll go ahead and merge.

**Comment by audreyfeldroy** [comment]
Thanks again @marekrozmus! And thanks for the friendly reminder.

**Pull request merged**
