### PR TITLE
JS-0739: Prefer to use anchors in a better way

### PR DESCRIPTION
**Pull request by kenanchristian**
Fix issues identified by DeepSource #27

This PR fixes the missing anchor anti-pattern detected by DeepSource [here](https://deepsource.io/gh/margaritahumanitarian/helpafamily/issue/JS-0739/occurrences?page=1)

### CODE REVIEW

**Review by RedFox0x20 — APPROVED** [review]
Thanks for these changes!

**Review by marekrozmus — COMMENTED** [review]
Thanks for the fix. One question - why is the order of class names changed?

**Comment by kenanchristian** [comment]
> Thanks for the fix. One question - why is the order of class names changed?

@marekrozmus Happy to help!
Hmm, I think it's an extension that I have, it's sorted the tailwind classes automatically. Should I revert those back?

**Review by audreyfeldroy — APPROVED** [review]
@kenanchristian Great work on this, thanks! About your extension auto-sorting the Tailwind classes, we'll accept this but in the future kindly separate that into a commit or PR of its own. 

Thanks for the helpful reviews @marekrozmus and @RedFox0x20 🙏

**Pull request merged**
