### PR TITLE
add focus ring to cards to improve site interactivity

### PR DESCRIPTION
**Pull request by GrungeKarma**
I am proposing adding hover rings to improve the interactivity of the page. Let me know what you think.

### CODE REVIEW

**Comment by marekrozmus** [comment]
Please add some screenshot or GIF when UI changes are made so we could see how it looks 🙂

**Comment by GrungeKarma** [comment]
Sorry, I thought that is what the Netlify Preview was for. Here is a link to a gif. 
https://imgur.com/a/2644gQv

**Comment by marekrozmus** [comment]
:D my bad. Sorry. I didn't used to those previews and forgot about them. You are absolutely right :)

**Comment by GrungeKarma** [comment]
No problem. I am still figuring this out, so I wanted to be sure.

**Comment by audreyfeldroy** [comment]
Your usage of a PR as a proposal here is great @GrungeKarma!

I think the focus rings are super interesting, and I love that you're experimenting with subtle UX improvements. My impressions are overall in favor of this PR with a little modification:

Pros:
* Helps the reader focus on reading one particular card. There's a lot of information so the eyes tend to scan the rest of the page, and the focus ring helps the reader recenter.
* Adds a nice feeling of dynamic interactivity.

Cons:
* Potentially creates a little usability confusion, as when the focus ring lights up, I want to click on the card. Perhaps resolvable by making the whole card clickable?

Also consider these related design issues:
* #83 since the background color affects the focus ring color
* #39 since the logo colors may require page color tweaks

As the next step forward, @GrungeKarma I suggest:
* Adding a commit to this PR to resolve the merge conflicts
* Experimenting with making the whole card clickable and letting us know your thoughts

**Comment by GrungeKarma** [comment]
Due to the changes in structure, I am going to close this request and open a new one

**Pull request closed without merging**
