### PR TITLE
Update Discord link

### PR DESCRIPTION
**Pull request by Jayita10**
Fixed issue #205

### CODE REVIEW

**Review by marekrozmus — CHANGES_REQUESTED** [review]
There is a problem with inviter:
invite_issue

@audreyfeldroy could we generate some general link with invitation without any inviter?

**Comment by LowLifeArcade** [comment]
> @audreyfeldroy could we generate some general link with invitation without any inviter?

Unfortunately, that's not how Discord works. But I do think it would be better if @audreyfeldroy were the inviter. We'll get that link for you soon @Jayita10.

**Comment by LowLifeArcade** [comment]
Here you go @Jayita10 https://discord.gg/WsmqrcGqyE

Please replace the current link with this one! 🎃

**Review by marekrozmus — APPROVED** [review]
LGTM

**Review by LowLifeArcade — APPROVED** [review]
Looks great, @Jayita10! Thank you 🥳

**Pull request merged**
