### PR TITLE
🚀 feat: hot meal day section new design

### LINKED ISSUE #338: ⚡️ 🏠 📄 ⚡️ Hot Meal Day Section
**What should we change and why?**

We want to spruce it up. In the [Figma File](https://www.figma.com/file/nLwxUWpunk8SgvjVpyE2gd/MHF-Boards?node-id=0%3A1) we add a background which you will export as an svg to implement. Also, there are some detail changes with the buttons and a new font for the `quote`.

Screen Shot 2021-11-09 at 1 52 27 PM

### PR DESCRIPTION
**Pull request by akshitarora921**
### This PR: 
* created new design for hot meal day section
* fixes card paragraph color for the card in dark mode

fixes #338 

### Self-Review Checklist
- [x] PR title is clear with proper spelling and grammar
- [x] PR description contains a bulleted list of changes contained in the PR
- [x] PR links to relevant issues, with keywords to auto-close any issues fully resolved upon merge
- [x] All automated checks passed
- [x] Any variables introduced are named clearly and explicitly

### CODE REVIEW

**Comment by akshitarora921** [comment]
I am getting this error while running the build command  in this branch as well as main branch also.
```Error occurred prerendering page "/landing-page". Read more: https://nextjs.org/docs/messages/prerender-error
Error: Error serializing `.FORM_ID` returned from `getStaticProps` in "/landing-page".
Reason: `undefined` cannot be serialized as JSON. Please use `null` or omit this value.
    at isSerializable (C:\Users\Akshit Arora\Desktop\projects\helpafamily\node_modules\next\dist\lib\is-serializable-props.js:39:19)
    at C:\Users\Akshit Arora\Desktop\projects\helpafamily\node_modules\next\dist\lib\is-serializable-props.js:46:66
    at Array.every (<anonymous>)
    at isSerializable (C:\Users\Akshit Arora\Desktop\projects\helpafamily\node_modules\next\dist\lib\is-serializable-props.js:43:39)
    at Object.isSerializableProps (C:\Users\Akshit Arora\Desktop\projects\helpafamily\node_modules\next\dist\lib\is-serializable-props.js:66:12)
    at renderToHTML (C:\Users\Akshit Arora\Desktop\projects\helpafamily\node_modules\next\dist\server\render.js:385:97)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async C:\Users\Akshit Arora\Desktop\projects\helpafamily\node_modules\next\dist\export\worker.js:273:36
    at async Span.traceAsyncFn (C:\Users\Akshit Arora\Desktop\projects\helpafamily\node_modules\next\dist\telemetry\trace\trace.js:60:20)
info  - Generating static pages (9/9)
```

**Comment by LowLifeArcade** [comment]
This looks great, @akshitarora921. You've converted the look nicely and faithfully to the design!

We do have an issue in mobile though. Currently the site looks like this between the Hot Meal Day section and the Card Carousel: 

Screen Shot 2021-12-08 at 1 10 28 PM

In your PR we see this:

Screen Shot 2021-12-08 at 1 10 37 PM

**Comment by akshitarora921** [comment]
@LowLifeArcade, Should we remove background for `CardLayout` in mobile view?

**Comment by akshitarora921** [comment]
I found another issue also related to `z-index`
image

**Comment by LowLifeArcade** [comment]
Nice @akshitarora921! You fixed everything and it looks great 💯. Merging! 🦖 ✨

**Pull request merged**
