### PR TITLE
Deepsource: Added Language prop in html and replaced if-else by ternary operator

### PR DESCRIPTION
**Pull request by metavinayak**
Based on Deepsource suggestions:

1) Added Language prop in html in pages/404.html

Screenshot from 2021-10-02 18-22-36
l
2) Replaced if-else statement with ternary operator in pages/fund.js

Screenshot from 2021-10-02 18-41-09

### CODE REVIEW

**Comment by metavinayak** [comment]
From
Fix issues identified by DeepSource #27

**Comment by metavinayak** [comment]
Also there is a minor improvement possibility on home page. The mailto link in the Electronics Drop-Off Box is of yellow color which is difficult to read. It can be changed to dark green or blue for better visibility.If change needed please tell.

Screenshot from 2021-10-02 19-12-34

**Review by RedFox0x20 — APPROVED** [review]
Thanks for the deepsource changes! The ternary is quite nice for minimised repetition.

**Review by LowLifeArcade — APPROVED** [review]
Nice stuff @metavinayak 🥳 Thank you for doing this!

**Comment by metavinayak** [comment]
> Also there is a minor improvement possibility on home page. The mailto link in the Electronics Drop-Off Box is of yellow color which is difficult to read. It can be changed to dark green or blue for better visibility.If change needed please tell.
> 
> Screenshot from 2021-10-02 19-12-34

Should I change this too ?

**Pull request merged**
